### PR TITLE
Add contributors page

### PR DESCRIPTION
**Pull request by ollie-codeaid**
Sorry - really haven't had a great deal of time to spend on this.

I've pushed this very very basic mockup to facilitate some discussion. For the time being I've just put the contributors lists as a static json file. We could pull the technical contributors directly from github but I think it would be nice to have a little more control over name, role type etc.

For non-technical contributors and organisations we would eventually want some form of backend so that we can update without having to push code. For the time being I think this is fine though.

### CODE REVIEW

**Comment by mindoodoo** [comment]
I think this is good enough for the time being as we don't have tons of contributors either.
It would be great to have a small field for "roles", although I only see how that would workout for the meta part of things (such as technical lead, project lead, etc...) What "roles" would we put for technical contributors ? Would we differenciate them based on the type of technical contribution (ie: data engineering vs front end) ?

This "role" field could also be a small line describing how that one person contributed. Just an idea though. It stems from particular cases that I don't see the "role" being enough for (I'm thinking for exampe about the person that made the logo).

Also having a small piece of text just saying to get in touch with me in case you don't see your name listed here might be a good idea as we'll most likely keep it as a static JSON file for the time being (for simplicity's sake), and new contributors might not know that.

**Comment by ollie-codeaid** [comment]
Ok cool that makes sense.

@mindoodoo I'm pretty sure you're best placed to compile a list of non-technical contributors? Although feel free to defer to someone else if you think they would have a clearer picture. Maybe this list should be maintained on Notion? Once you've started putting that list together the 'roles' might just fall into place - I don't see a problem with keeping them very high level though.

For technical contributors we could just ask people to submit a PR to add themselves?

Do you have any further organisations you would like to add? Again maybe Notion would be the best place to keep that?

**Comment by mindoodoo** [comment]
@ollie-codeaid Yeah you're idea to maintain the list on notion is a good idea, I'll look into that.
I'll try to compile a list of non technical contributors, and then you guys will be able to take a look at it and tell me if I forgot anything. Should I maintain a list of technical contributors too ?
I'll also do the same for organizations.

I think for technical contributors, once they make a PR, we should always comment on the PR saying to add themselves as a technical contributor if they're not already. That would avoid people having to make dedicated PRs to that.

**Comment by mindoodoo** [comment]
@ollie-codeaid I put all the contributors in a table on Notion. I probably missed some but I think it's a good start. I also couldn't find the name of the person that made the logo so we'll have to see for that one.

Also a cool and simple thing we could do, is alternate a row of three contributors, a row of two, row of three...etc... I hope I'm not too confusing haha

**Pull request merged**
